#!/usr/bin/env bash
# if ./index -r, this deletes
# the remote database and re-builds it

set -e

declare RESET SSH_TARGET
RESET=
SSH_TARGET="${SSH_TARGET:-vultr}"

# if we want to delete the remote database
[[ "$1" == "-r" ]] && RESET=1
declare -rx RESET

if ((RESET)); then
	echo "Reindexing..."
else
	echo "Indexing..."
fi

wait-for-internet -q --timeout 30 || exit 0

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

# sync osrs images
REMSYNC_PUBLIC=1 "${REPOS}/vps/remsync" "$(python3 -m my.utils.backup_to runelite_screenshots)" 2>&1 >/dev/null || exit $?

# temporary dir for new data
TMPDIR="$(mktemp -d)"
# https://sean.fish/d/.local/share/shortcuts/epoch?dark
PICKLE="${TMPDIR}/$(epoch).pickle" || exit $?

# run an index
my_feed index "$PICKLE" || exit $?

wait-for-internet -q --timeout 30 || exit 0

# delete remote pickle's if we want to reset
if [[ -n "$RESET" ]]; then
	ssh "${SSH_TARGET}" 'rm -vf ~/code/my_feed/backend/data/*.pickle'
fi

# copy up to the server
scp "${PICKLE}" "${SSH_TARGET}":~/code/my_feed/backend/data

# delete temp file
rm -f "${PICKLE}"

if [[ -n "$RESET" ]]; then
	echo 'Deleting database...'
	set -x
	ssh "${SSH_TARGET}" 'rm -vf ~/code/my_feed/backend/feeddata.sqlite && ~/vps/super --ctl restart feed-backend'
	set +x
	echo '(remote is rebuilding database, should be done in a couple seconds)'
else
	# otherwise this is just new data, just ping the server to check for new files
	echo 'Running update...'
	curl -sL 'https://sean.fish/feed_api/check'
	echo
fi
