#!/usr/bin/env zsh
# wrapper script which:
# - runs the python checker to remove evry tags if data has expired
# - runs jobs to update local cache files
# - runs a update to update the remote database

set -u

main() {
	source "$HPIDATA/personal_aliases" 2>/dev/null
	source "$HPIDATA/tokens"
	wait-for-internet --quiet --timeout 10 || exit 0
	EXPIRED="$(MY_FEED_BG=1 feed_check "$@")" || return $?
	if [[ -n "$EXPIRED" ]]; then
		printf 'Expired: %s\n' "$EXPIRED"
		bgproc_on_machine -qo                       # update local data
		rm -fv "$(evry location -my-feed-index-bg)" # reset background index
		bgproc_on_machine -qo                       # run background index
	fi
}

main "$@" || exit $?
