#!/usr/bin/env bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

ROOT_DIR="$(realpath "${THIS_DIR}/../")"
export DATABASE_URI
export CGO_ENABLED=1

go build -o ./main -ldflags "-X main.RootDir=${ROOT_DIR}" ./main.go
