#!/usr/bin/env bash
# simple wrapper script to setup environment variables

source <(grep BEARER_SECRET ../.env)
if [[ -z "$BEARER_SECRET" ]]; then
  echo "Couldn't get BEARER_SECRET from .env file"
fi
export BEARER_SECRET
./main "$@"
